using FastMember;
using Npgsql;

namespace robot_api.Persistence
{
    public static class ExtensionMethods
    {
        public static void MapTo<T>(this NpgsqlDataReader dr, T entity)
        {
            if (entity == null)
                throw new ArgumentNullException(nameof(entity));
            var fastMember = TypeAccessor.Create(entity.GetType());
            var props = fastMember
                .GetMembers()
                .Select(x => x.Name)
                .ToDictionary(name => Normalize(name), name => name, StringComparer.Ordinal);
            for (int i = 0; i < dr.FieldCount; i++)
            {
                if (props.TryGetValue(Normalize(dr.GetName(i)), out var prop))
                    fastMember[entity, prop] = dr.IsDBNull(i) ? null : dr.GetValue(i);
            }
        }

        // Strip underscores and lower-case so snake_case DB columns (e.g. "created_date")
        // match PascalCase properties (e.g. "CreatedDate") generated by the Handlebars templates.
        private static string Normalize(string name) =>
            name.Replace("_", string.Empty).ToLowerInvariant();
    }
}
